# Generated by Django 6.0.3 on 2026-03-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_learningunit_owner_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
